baseURL = "https://qcarchive.molssi.org"
languageCode = "en-us"
title = "The MolSSI QCArchive"
theme = "small-apps-local"
summaryLength = "10"
paginate = 6

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.carousel.min.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.theme.green.min.css"
  [[params.plugins.css]]
  URL = "plugins/fancybox/jquery.fancybox.min.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/owl-carousel/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "plugins/fancybox/jquery.fancybox.min.js"
  [[params.plugins.js]]
  URL = "plugins/syotimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "/about"
  weight = 2

  [[menu.main]]
  name = "Using"
  URL = "/using"
  weight = 3
  
  [[menu.main]]
  name = "team"
  URL = "/team"
  weight = 4

  [[menu.main]]
  name = "QCA Projects"
  URL = "/projects"
  weight = 5
  
  [[menu.main]]
  name = "Contact"
  URL = "/contact"
  weight = 7

  [[menu.main]]
  weight = 8
  name = "Other Content"
  hasChildren = true

    [[menu.main]]
    parent = "Other Content"
    name = "License and Funding"
    URL = "/privacy"

    [[menu.main]]
    parent = "Other Content"
    name = "FAQ"
    URL = "/faq"


  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "/about"

  [[menu.footer]]
  name = "Using"
  URL = "/using"
  
  [[menu.footer]]
  name = "Contact"
  URL = "/contact"
  
  [[menu.footer]]
  name = "License and Funding"
  URL = "/privacy"

  [[menu.footer]]
  name = "FAQ"
  URL = "/faq"


[params]
logo = "images/logo.png"
logoAlt = "images/logo-alt.png"
home = "Home"
# Meta data
description = "MolSSI's QC Archive Project"
author = "Daniel G. A. Smith, MolSSI, Levi N. Naden"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "37.2001382,"
mapLongitude = "-80.4105687"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

# footer
  [params.footer]

  # social icon
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-facebook"
  URL = "https://www.facebook.com/molssi/?fref=ts"

  [[params.footer.socialIcon]]
  icon = "tf-ion-social-twitter"
  URL = "https://twitter.com/MolSSI_NSF"
  
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-linkedin"
  URL = "https://www.linkedin.com/groups/13503505/profile"

  # call to action
 [params.cta]
  enable = true
  title = "Help contribute to the QC Archive"
  content = "Want to see your QC code in QC Archive? Find a bug? Have questions in general? Head to the GitHub page and contribute!"
  btnText = "To QC Archive GitHub"
  URL = "https://github.com/MolSSI/QCFractal"
