baseURL = "https://qcarchive.molssi.org"
languageCode = "en-us"
title = "The MolSSI QCArchive"
theme = "small-apps"
summaryLength = "10"
paginate = 6

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.carousel.min.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.theme.green.min.css"
  [[params.plugins.css]]
  URL = "plugins/fancybox/jquery.fancybox.min.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/owl-carousel/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "plugins/fancybox/jquery.fancybox.min.js"
  [[params.plugins.js]]
  URL = "plugins/syotimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "/about"
  weight = 2

  [[menu.main]]
  name = "Get Started"
  URL = "/getstarted"
  weight = 3

  [[menu.main]]
  name = "Blog"
  URL = "/blog"
  weight = 4
  

  [[menu.main]]
  weight = 8
  name = "Ecosystem"
  hasChildren = true

    [[menu.main]]
    parent = "Ecosystem"
    name = "QCA Projects"
    URL = "/projects"

    [[menu.main]]
    parent = "Ecosystem"
    name = "Community"
    URL = "/community"

    [[menu.main]]
    parent = "Ecosystem"
    name = "Use Cases"
    URL = "/faq"

    [[menu.main]]
    parent = "Ecosystem"
    name = "Team"
    URL = "/team"

    # [[menu.main]]
    # parent = "FAQ"
    # name = "License and Funding"
    # URL = "/privacy"
  

  [[menu.main]]
  weight = 9
  name = "Documentation"
  hasChildren = true

    [[menu.main]]
    parent = "Documentation"
    name = "Tutorials "
    URL = "http://docs.qcarchive.molssi.org/"

    [[menu.main]]
    parent = "Documentation"
    name = "QCPortal "
    URL = "http://docs.qcarchive.molssi.org/projects/qcportal/"

    [[menu.main]]
    parent = "Documentation"
    name = "QCFractal "
    URL = "http://docs.qcarchive.molssi.org/projects/qcfractal/"

    [[menu.main]]
    parent = "Documentation"
    name = "QCEngine "
    URL = "http://docs.qcarchive.molssi.org/projects/qcengine/"

    [[menu.main]]
    parent = "Documentation"
    name = "QCElemental "
    URL = "http://docs.qcarchive.molssi.org/projects/qcelemental/"

  [[menu.main]]
  weight = 10
  name = "GitHub"
  hasChildren = true

    [[menu.main]]
    parent = "GitHub"
    name = "QCPortal"
    URL = "https://github.com/MolSSI/QCFractal"

    [[menu.main]]
    parent = "GitHub"
    name = "QCFractal"
    URL = "https://github.com/MolSSI/QCFractal"

    [[menu.main]]
    parent = "GitHub"
    name = "QCEngine"
    URL = "https://github.com/MolSSI/QCEngine"

    [[menu.main]]
    parent = "GitHub"
    name = "QCElemental"
    URL = "https://github.com/MolSSI/QCElemental"


  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "/about"

  [[menu.footer]]
  name = "Using"
  URL = "/using"
  
  # [[menu.footer]]
  # name = "Contact"
  # URL = "/contact"
  
  [[menu.footer]]
  name = "License and Funding"
  URL = "/privacy"

  [[menu.footer]]
  name = "FAQ"
  URL = "/faq"


[params]
logo = "images/logo.png"
logoAlt = "images/logo-alt.png"
# home = "Home"
# Meta data
description = "MolSSI's QC Archive Project"
author = "The Molecular Sciences Software Institute"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "37.2001382,"
mapLongitude = "-80.4105687"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "UA-136219377-1"

  # Preloader
  [params.preloader]
  enable = true

# footer
  [params.footer]

  # social icon
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-facebook"
  URL = "https://www.facebook.com/molssi/?fref=ts"

  [[params.footer.socialIcon]]
  icon = "tf-ion-social-twitter"
  URL = "https://twitter.com/MolSSI_NSF"
  
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-linkedin"
  URL = "https://www.linkedin.com/groups/13503505/profile"

  # call to action
 [params.cta]
  enable = true
  title = "Help contribute to the QC Archive"
  content = "Want to see your QC code in QC Archive? Find a bug? Have questions in general? Head to the GitHub page and contribute!"
  btnText = "To QCArchive GitHub"
  URL = "https://github.com/MolSSI/QCFractal"
